// <auto-generated />
using System;
using CaseTecnico.MRA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaseTecnico.MRA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115192636_UpdateArquivo_Type_Campos_Estabelecimento_Sequencia")]
    partial class UpdateArquivo_Type_Campos_Estabelecimento_Sequencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.Arquivo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("ArquivoStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estabelecimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstruturaImportada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PeriodoFinal")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("PeriodoInicial")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Sequencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificador");

                    b.HasIndex("ArquivoStatusId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Arquivos", (string)null);
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.ArquivoStatus", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificador");

                    b.ToTable("ArquivoStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Identificador = new Guid("8b44e4f4-2d8b-437f-ad3c-ee0d77ef97b0"),
                            DataInsercao = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Recepcionado"
                        },
                        new
                        {
                            Identificador = new Guid("d788bcaf-cdb2-495c-985d-355ce1157544"),
                            DataInsercao = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Não Recepcionado"
                        });
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Identificador");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            Identificador = new Guid("3a86fd10-725f-4143-ae55-7f127bc85a4e"),
                            DataInsercao = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "UfCard"
                        },
                        new
                        {
                            Identificador = new Guid("73c71cf2-2681-40d8-ab7f-ceb0b65aaf86"),
                            DataInsercao = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "FagammonCard"
                        });
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.LogErro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("DataInsercao")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("InnerException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificador");

                    b.ToTable("LogErros", (string)null);
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.Arquivo", b =>
                {
                    b.HasOne("CaseTecnico.MRA.Domain.Entities.ArquivoStatus", "ArquivoStatus")
                        .WithMany("Arquivos")
                        .HasForeignKey("ArquivoStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseTecnico.MRA.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Arquivos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArquivoStatus");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.ArquivoStatus", b =>
                {
                    b.Navigation("Arquivos");
                });

            modelBuilder.Entity("CaseTecnico.MRA.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
