//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseTecnico.MRA.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseTecnico.MRA.Application.Common.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo importado deve conter a etensão .txt.
        /// </summary>
        internal static string ArquivoImpDeveConterExtensaoTXT {
            get {
                return ResourceManager.GetString("ArquivoImpDeveConterExtensaoTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: O campo {1} encontra-se inválido..
        /// </summary>
        internal static string ArquivoImpLinhaCampoInvalido {
            get {
                return ResourceManager.GetString("ArquivoImpLinhaCampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: Identificado como empresa: {1} deve conter uma quantidade de {3} caracteres..
        /// </summary>
        internal static string ArquivoImpLinhaEmpresaIncorretaQtd {
            get {
                return ResourceManager.GetString("ArquivoImpLinhaEmpresaIncorretaQtd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linha {0}: Não possui a empresa no formato..
        /// </summary>
        internal static string ArquivoImpLinhaEmpresaInexistente {
            get {
                return ResourceManager.GetString("ArquivoImpLinhaEmpresaInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo importado encontra-se vazio..
        /// </summary>
        internal static string ArquivoImpSemInfo {
            get {
                return ResourceManager.GetString("ArquivoImpSemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} encontra-se o inválido..
        /// </summary>
        internal static string CampoInvalido {
            get {
                return ResourceManager.GetString("CampoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        internal static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no máximo {1} caracteres..
        /// </summary>
        internal static string CampoTamanhoMaxInvalido {
            get {
                return ResourceManager.GetString("CampoTamanhoMaxInvalido", resourceCulture);
            }
        }
    }
}
